package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

var (
	// Diff command specific flags
	diffApplyFlag bool
)

var diffCmd = &cobra.Command{
	Use:   "diff",
	Short: "Show and optionally apply a patch",
	Long: `Show a diff/patch generated by the LLM and optionally apply it.
Can be used to preview changes before applying them.`,
	RunE: runDiff,
}

func init() {
	diffCmd.Flags().BoolVar(&diffApplyFlag, "apply", false, "Apply the patch")
}

func runDiff(cmd *cobra.Command, args []string) error {
	// TODO: Implement diff functionality
	fmt.Println("Diff command")

	return nil
}
